# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 480)
        MainWindow.setStyleSheet("background-color: rgb(213, 207, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.time_shower = QtWidgets.QTableWidget(self.centralwidget)
        self.time_shower.setGeometry(QtCore.QRect(10, 10, 391, 451))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.time_shower.setFont(font)
        self.time_shower.setStyleSheet("border: 0px")
        self.time_shower.setObjectName("time_shower")
        self.time_shower.setColumnCount(2)
        self.time_shower.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.time_shower.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_shower.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuScreen_Saver = QtWidgets.QMenu(self.menuOptions)
        self.menuScreen_Saver.setObjectName("menuScreen_Saver")
        self.menuTelegram_Bot = QtWidgets.QMenu(self.menuOptions)
        self.menuTelegram_Bot.setObjectName("menuTelegram_Bot")
        self.menuAboutg = QtWidgets.QMenu(self.menubar)
        self.menuAboutg.setObjectName("menuAboutg")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreator = QtWidgets.QAction(MainWindow)
        self.actionCreator.setObjectName("actionCreator")
        self.guide_act = QtWidgets.QAction(MainWindow)
        self.guide_act.setObjectName("guide_act")
        self.save_act = QtWidgets.QAction(MainWindow)
        self.save_act.setObjectName("save_act")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.clear_act = QtWidgets.QAction(MainWindow)
        self.clear_act.setObjectName("clear_act")
        self.chpass_act = QtWidgets.QAction(MainWindow)
        self.chpass_act.setObjectName("chpass_act")
        self.s_limit_act = QtWidgets.QAction(MainWindow)
        self.s_limit_act.setObjectName("s_limit_act")
        self.s_flag_act = QtWidgets.QAction(MainWindow)
        self.s_flag_act.setObjectName("s_flag_act")
        self.s_interval_act = QtWidgets.QAction(MainWindow)
        self.s_interval_act.setObjectName("s_interval_act")
        self.actionToken = QtWidgets.QAction(MainWindow)
        self.actionToken.setObjectName("actionToken")
        self.actionTurn_on_off = QtWidgets.QAction(MainWindow)
        self.actionTurn_on_off.setObjectName("actionTurn_on_off")
        self.actionChange_password = QtWidgets.QAction(MainWindow)
        self.actionChange_password.setObjectName("actionChange_password")
        self.menuScreen_Saver.addAction(self.s_flag_act)
        self.menuScreen_Saver.addAction(self.s_limit_act)
        self.menuScreen_Saver.addAction(self.s_interval_act)
        self.menuTelegram_Bot.addAction(self.actionToken)
        self.menuTelegram_Bot.addAction(self.actionTurn_on_off)
        self.menuTelegram_Bot.addAction(self.actionChange_password)
        self.menuOptions.addAction(self.menuTelegram_Bot.menuAction())
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.menuScreen_Saver.menuAction())
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.chpass_act)
        self.menuAboutg.addAction(self.guide_act)
        self.menuFile.addAction(self.save_act)
        self.menuFile.addAction(self.clear_act)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuAboutg.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "T&C"))
        item = self.time_shower.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        item = self.time_shower.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duration of use"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuScreen_Saver.setTitle(_translate("MainWindow", "Screen Saver"))
        self.menuTelegram_Bot.setTitle(_translate("MainWindow", "Telegram Bot"))
        self.menuAboutg.setTitle(_translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionCreator.setText(_translate("MainWindow", "Creator"))
        self.guide_act.setText(_translate("MainWindow", "Guide"))
        self.save_act.setText(_translate("MainWindow", "Save history"))
        self.actionOpen.setText(_translate("MainWindow", "Clear"))
        self.clear_act.setText(_translate("MainWindow", "Clear history"))
        self.chpass_act.setText(_translate("MainWindow", "Change Password"))
        self.s_limit_act.setText(_translate("MainWindow", "Set count photo"))
        self.s_flag_act.setText(_translate("MainWindow", "Turn on/off"))
        self.s_interval_act.setText(_translate("MainWindow", "Set interval"))
        self.actionToken.setText(_translate("MainWindow", "Token"))
        self.actionTurn_on_off.setText(_translate("MainWindow", "Turn on/off"))
        self.actionChange_password.setText(_translate("MainWindow", "Change password"))
